name: Run Every 10 Minutes

on:
    schedule:
     - cron: '*/10 * * * *'
    workflow_dispatch:

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Install requirements
              run: pip install -r project_requirements.txt
            - name: run script
              run: python complete_stock_monitor.py
        